name: Run Tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go: [ '1.16', '1.17' ]

    runs-on: ubuntu-20.04

    name: Go ${{ matrix.go }} Tests
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Verify dependencies
        run: go mod verify

      - name: Build
        run: go build -v ./...

      - name: Run Test
        run: go test -v ./...

      - name: Run Coverage
        run: go test -v -cover ./...